- name: apparmor-libreoffice - Shutdown AppArmor service
  ansible.builtin.service:
    name: apparmor.service
    state: stopped
  listen: "restart apparmor"

- name: apparmor-libreoffice - Remove AppArmor kernel rules
  ansible.builtin.command: aa-teardown
  listen: "restart apparmor"

- name: apparmor-libreoffice - Start  AppArmor service
  ansible.builtin.service:
    name: apparmor.service
    state: started
  listen: "restart apparmor"